### ISSUE TITLE
Version for raspberrypi zero w?

### ISSUE THREAD

**Issue by SirPounce** [skarbat/kivypie#4]
I'm wondering if you have any ambition to make this available in the future and if not if you have any ideas on where to start to modify in order to make that happen.

**Comment by skarbat** [comment]
It's a good idea for which I've yet to get the chance to delve into, thanks for raising it @SirPounce !
Opening a discussion thread [here](https://groups.google.com/forum/#!topic/kivypie/1b8aXBjH248)
