### ISSUE TITLE
chroot: failed to run command '/bin/bash': No such file or directory

### ISSUE THREAD

**Issue by bojeckkk** [skarbat/kivypie#5]
Using Ubuntu 16.04.3 LTS, after solving all dependencies and running build.sh, this happens:

`Running in --build-all mode
Removing qcow image /home/krystian/osimages/kivypie.qcow
Removing uncompressed backing image /home/krystian/osimages/kivypie.img
Uncompressing image /home/krystian/osimages/pipaos-lulo-xgui-4.6.img.gz into /home/krystian/osimages/kivypie.img
Creating qcow image /home/krystian/osimages/kivypie.qcow of new forced size 3.5G
Formatting '/home/krystian/osimages/kivypie.qcow', fmt=qcow2 size=3758096384 backing_file=/home/krystian/osimages/kivypie.img encryption=off cluster_size=65536 lazy_refcounts=off refcount_bits=16
binding qcow image: /home/krystian/osimages/kivypie.qcow
mounting root partition /dev/nbd1p2 -> /tmp/kivypie
'/tmp/kivypie/etc/ld.so.preload' -> '/tmp/kivypie/etc/ld.so.preload-disabled'
mounting boot partition /dev/nbd1p1 -> /tmp/kivypie_boot
Mount done
Preparing sysroot for chroot to function correctly
cp: missing destination file operand after '/tmp/kivypie/usr/bin'
Try 'cp --help' for more information.
chroot: failed to run command '/bin/bash': No such file or directory
Preparation done
Renew done
'/tmp/kivypie/etc/ld.so.preload-disabled' -> '/tmp/kivypie/etc/ld.so.preload'
unbinding /home/krystian/osimages/kivypie.qcow
umount: /tmp/kivypie/sys/fs/cgroup/systemd: mountpoint not found
umount: /tmp/kivypie/sys/fs/cgroup: not mounted
/dev/nbd1 disconnected
Unmount done
Connecting image /home/krystian/osimages/kivypie.qcow to find and expand last partition
Partition number: 2 start: 121MB end: 1940MB size: 1819MB type: ext4
/dev/nbd1p2: 31313/111104 files (0.3% non-contiguous), 200193/444160 blocks
resize2fs 1.42.13 (17-May-2015)
Resizing the filesystem on /dev/nbd1p2 to 888064 (4k) blocks.
The filesystem on /dev/nbd1p2 is now 888064 (4k) blocks long.

Image partition expanded successfully, new layout:
Partition number: 2 start: 121MB end: 3758MB size: 3638MB type: ext4
/dev/nbd1 disconnected
binding qcow image: /home/krystian/osimages/kivypie.qcow
mounting root partition /dev/nbd1p2 -> /tmp/kivypie
'/tmp/kivypie/etc/ld.so.preload' -> '/tmp/kivypie/etc/ld.so.preload-disabled'
mounting boot partition /dev/nbd1p1 -> /tmp/kivypie_boot
Mount done
sysroot executing: /bin/bash -c "echo 'kivypie v1.0 - Sat Jan 13 06:48:03 2018' > /etc/kivypie_version"
chroot: failed to run command '/bin/bash': No such file or directory
sysroot executing: /bin/bash -c "echo 'kivypie' > /etc/hostname"
chroot: failed to run command '/bin/bash': No such file or directory
sysroot executing: /bin/bash -c "echo '127.0.0.1 localhost' > /etc/hosts"
chroot: failed to run command '/bin/bash': No such file or directory
sysroot executing: /bin/bash -c "echo '127.0.0.1 kivypie' >> /etc/hosts"
chroot: failed to run command '/bin/bash': No such file or directory
'config.txt' -> '/tmp/kivypie_boot/config.txt'
'README-kivypie' -> '/tmp/kivypie_boot/README-kivypie'
'LICENSE' -> '/tmp/kivypie_boot/LICENSE-kivypie'
Copying kivy installation script install-kivy.sh -> /home/krystian/xtmp/install-kivy.sh
sysroot executing: /bin/bash -c "cd /tmp ; ./install-kivy.sh 1.10.0"
chroot: failed to run command '/bin/bash': No such file or directory
ERROR: kivy installation script reported problems rc=127
'/tmp/kivypie/etc/ld.so.preload-disabled' -> '/tmp/kivypie/etc/ld.so.preload'
unbinding /home/krystian/osimages/kivypie.qcow
umount: /tmp/kivypie/sys/fs/cgroup/systemd: mountpoint not found
umount: /tmp/kivypie/sys/fs/cgroup: not mounted
/dev/nbd1 disconnected
Unmount done
Converting image /home/krystian/osimages/kivypie.qcow...
Process finished in 19.7754240036 secs - image ready at kivy-pie-1.0.img
chroot: failed to run command 'which': No such file or directory
dispmanx_vncserver - FAILED
chroot: failed to run command 'which': No such file or directory
raspi2png - FAILED
chroot: failed to run command 'su': No such file or directory
sysop user - FAILED
default python version - PASS
kivy for default python - FAILED
kivy for python2 - FAILED
kivy for python3 - FAILED
user sysop kivy configuration file - FAILED
chroot: failed to run command 'ls': No such file or directory
kivy root configuration file - FAILED
chroot: failed to run command 'su': No such file or directory
kivy garden - FAILED
chroot: failed to run command 'su': No such file or directory
python requests - FAILED
chroot: failed to run command 'su': No such file or directory
python BeautifulSoup - FAILED
chroot: failed to run command 'su': No such file or directory
pip3 - FAILED
umount: /tmp/kivypie/sys/fs/cgroup/systemd: mountpoint not found
umount: /tmp/kivypie/sys/fs/cgroup: not mounted
`

**Comment by skarbat** [comment]
You seem to be missing the static ARM emulator, so everything else fails.

 * https://github.com/skarbat/xsysroot/blob/master/xsysroot#L226

**Comment by bojeckkk** [comment]
You are right, I somehow missed that dependency yesterday. Sorry.
